# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zufang', '0002_auto_20160703_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zufang.Fang')),
                ('likinguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zufang.UserProfile')),
            ],
        ),
    ]
