# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zufang', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='fang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='zufang.Fang'),
        ),
        migrations.AlterField(
            model_name='like',
            name='likinguser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_users', to='zufang.UserProfile'),
        ),
    ]
